### PR TITLE
Add a license

### LINKED ISSUE #11: Repo needs a license
To make it actually open source.

### PR DESCRIPTION
**Pull request by bhazelton**
closes #11

### CODE REVIEW

**Comment by bhazelton** [comment]
@nicholebarry @rlbyrne @mwilensky768 @PyxieLouStar are you all comfortable with adding an open source license to this repo?

**Comment by PyxieLouStar** [comment]
yes, sounds good.

**Comment by rlbyrne** [comment]
Yes, we should do this

**Comment by mwilensky768** [comment]
Yep! Sounds good.

**Pull request merged**
